import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Button from "react-bootstrap/Button";
import Container from "react-bootstrap/Container";
import Nav from "react-bootstrap/Nav";
import Navbar from "react-bootstrap/Navbar";
import NavDropdown from "react-bootstrap/NavDropdown";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="container">
          <div className="d-flex py-3">
            <div className="me-3">
              <Image src={"/LOGO.png"} width={192} height={53} alt="Logo" />
            </div>
            <div className="fs_24">
              <div className="ev_my">
                <span className="date">17 | 18 | 19</span> Jan’24 <br />
              </div>
              <div className="venue">
                Helipad Exhibition Centre, Gandhinagar, <br />
                Gujarat, India
              </div>
            </div>
          </div>
          <Navbar bg="dark" variant="dark" expand="lg">
            <Navbar.Toggle aria-controls="basic-navbar-nav" />
            <Navbar.Collapse id="basic-navbar-nav">
              <Nav className="me-auto">
                <Nav.Link href="#home">Home</Nav.Link>
                <Nav.Link href="#link">Concurrent Events</Nav.Link>
                <Nav.Link href="#link">About</Nav.Link>
                <Nav.Link href="#link">Exhibitor</Nav.Link>
                <Nav.Link href="#link">Visitor</Nav.Link>
                <Nav.Link href="#link">Media</Nav.Link>
                <Nav.Link href="#link">Contact Us</Nav.Link>
                <NavDropdown title="Dropdown" id="basic-nav-dropdown">
                  <NavDropdown.Item href="#action/3.1">Action</NavDropdown.Item>
                  <NavDropdown.Item href="#action/3.2">
                    Another action
                  </NavDropdown.Item>
                  <NavDropdown.Item href="#action/3.3">
                    Something
                  </NavDropdown.Item>
                  <NavDropdown.Divider />
                  <NavDropdown.Item href="#action/3.4">
                    Separated link
                  </NavDropdown.Item>
                </NavDropdown>
              </Nav>
            </Navbar.Collapse>
          </Navbar>
        </div>
      </header>

      <main>
        <div className="bg_light_green">
          <div class="container pt-60">
            <div class="row g-0">
              <div class="col-9">
                <div className="slider">
                  <picture>
                    <img className="w-100" src={"/banner.png"} alt="Banner" />
                  </picture>
                </div>
              </div>
              <div class="col-3 bg_blue p-4 text-center">
                <div className="title text-white">
                  Concurrent <span className="fw-semibold">Events</span>
                </div>
                <div className="mt-3">
                  <picture>
                    <img
                      className="w-100"
                      src={"/TSI_event.png"}
                      alt="Banner"
                    />
                  </picture>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-5">
          sdfsdfsdf
        </div>
        <Button as="a" variant="primary">
          Button as link
        </Button>
      </main>
    </>
  );
}
